services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: inventory-api
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - inventory-network
    restart: always
    volumes:
      - .:/app #hot reload source code if developing locally
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G

networks:
  inventory-network:
    driver: bridge
    name: inventory-network