version: '3.8'

services:
  app:
    build: .
    container_name: inventory-api
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI
      - DATABASE_NAME
      - JWT_SECRET
    networks:
      - inventory-network
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  inventory-network:
    driver: bridge
