version: '3.8'

services:
  app:
    build: .
    container_name: inventory-api
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - inventory-network
    restart: always
    volumes:
      - .:/app #hot reload source code if developing locally
    command: >
      /opt/venv/bin/python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env 

networks:
  inventory-network:
    driver: bridge
