services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: inventory-api
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - inventory-network
    restart: always
    volumes:
      - .:/app #hot reload source code if developing locally
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G

networks:
  inventory-network:
    driver: bridge
    name: inventory-network






























# docker run -d \
#   --name inventory-api \
#   --network inventory-network \
#   -p 8000:8000 \
#   -e MONGO_URI="your-mongo-uri-here" \
#   -e JWT_SECRET="your-jwt-secret-here" \
#   --restart always \
#   -v $(pwd):/app \
#   --cpus 2 \
#   --memory 1G \
#   --env-file .env \
#   your-image-name