version: '3.8'

services:
  app:
    build: .
    container_name: inventory-api
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - inventory-network
    restart: always
    volumes:
      - .:/app #hot reload source code if developing locally
    env_file:
      - .env 

networks:
  inventory-network:
    driver: bridge
